name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "lint"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "test"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "build"

  sast_dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "sast/dast"

  license_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "license check"
